### ISSUE TITLE
UPenn diagnostic "endpoint" page is unreachable

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/export_archivesspace_xml#39]
The [page UPenn uses to show us whether or not its EAD harvest worked successfully](https://findingaids.library.upenn.edu/admin/endpoints/SCIHIST) is currently unreachable.

Note that our export to S3 is working fine. We just don't know whether UPenn is harvesting those files from s3.

Because we check this page's status every day as part of our export workflow (see[ the heroku scheduler for the project](https://dashboard.heroku.com/apps/export-archivesspace-xml/scheduler) ), the nightly task is not reporting to HoneyBadger, which in turn is letting us know it's not receiving the nightly check-ins it's expecting.

**Comment by eddierubeiz** [comment]
I notified Sarah N. and Holly Jo Mengel at UPenn. Will update the ticket as needed.

**Comment by jrochkind** [comment]
Is that UPenn page a specifically created for us “diagnostic” page?  I wonder if we coudl actually check a live public page of some kind instead?  They don’t have much incentive to notice when a just-for-us diagnostic page goes down, or to fix it. 

Can we also (or do we already have) automated monitoring that actually checks our OWN endpoints are HTTP accessible with expected content?

A custom-for-us diagnostic page on THEIR end does not seem the optimal monitoring solution to me.

**Comment by eddierubeiz** [comment]
Response from Holly:
`Thank you so much for reaching out.  Usually something like this happens when a web site is updated, etc.; but since  it seems like you are not aware of anything like this, I sent your email to our IT team. As soon as I hear back from them, I will let you know!`

**Comment by eddierubeiz** [comment]
@archivistsarah - tagging you :)
